................F..F.F...F...F...
======================================================================
FAIL: test_float (unit.test_add.TestAdd.test_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jvgoliveira/PycharmProjects/QaTest/qatest/calculator/tests/unit/test_add.py", line 12, in test_float
    self.assertEqual(result, 6)
AssertionError: 5.7 != 6

======================================================================
FAIL: test_string (unit.test_add.TestAdd.test_string)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jvgoliveira/PycharmProjects/QaTest/qatest/calculator/tests/unit/test_add.py", line 16, in test_string
    self.assertEqual(result, 20)
AssertionError: '1010' != 20

======================================================================
FAIL: test_float (unit.test_divide.TestDivide.test_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jvgoliveira/PycharmProjects/QaTest/qatest/calculator/tests/unit/test_divide.py", line 12, in test_float
    self.assertEqual(result, 33)
AssertionError: 33.333333333333336 != 33

======================================================================
FAIL: test_float (unit.test_multiply.TestMultiply.test_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jvgoliveira/PycharmProjects/QaTest/qatest/calculator/tests/unit/test_multiply.py", line 12, in test_float
    self.assertEqual(result, 98)
AssertionError: 98.01 != 98

======================================================================
FAIL: test_float (unit.test_subtract.TestSubtract.test_float)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jvgoliveira/PycharmProjects/QaTest/qatest/calculator/tests/unit/test_subtract.py", line 12, in test_float
    self.assertEqual(result, 4)
AssertionError: 4.3 != 4

----------------------------------------------------------------------
Ran 33 tests in 0.003s

FAILED (failures=5)
